# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    # 
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(400, 389)
        window.setToolTipDuration(-2)
        self.pushButton = QtWidgets.QPushButton(window)
        self.pushButton.setGeometry(QtCore.QRect(160, 160, 75, 61))
        self.pushButton.setObjectName("pushButton")
        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)
        # when button pushed:
        self.pushButton.clicked.connect(self.button_pushed)
    
    def button_pushed(self):
        print("yoyo wassup homieee")

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Tic Tac Toe"))
        self.pushButton.setText(_translate("window", "press me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QDialog()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
